<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-24T16:21:58 IST" name="TestSuite" finished-at="2024-12-24T16:22:02 IST" duration-ms="3945">
    <groups>
    </groups>
    <test started-at="2024-12-24T16:21:58 IST" name="TestChrome" finished-at="2024-12-24T16:22:02 IST" duration-ms="3945">
      <class name="tests.TC002_LoginUser">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String)[pri:0, instance:tests.TC002_LoginUser@3d9c13b5]" started-at="2024-12-24T16:21:58 IST" name="setUp" finished-at="2024-12-24T16:21:59 IST" duration-ms="1019" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLoginUser()[pri:0, instance:tests.TC002_LoginUser@3d9c13b5]" started-at="2024-12-24T16:21:59 IST" name="testLoginUser" finished-at="2024-12-24T16:22:01 IST" duration-ms="2437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginUser -->
        <test-method signature="enterCredential(java.lang.String,java.lang.String)[pri:1, instance:tests.TC002_LoginUser@3d9c13b5]" started-at="2024-12-24T16:22:01 IST" name="enterCredential" data-provider="LoginData" finished-at="2024-12-24T16:22:02 IST" duration-ms="274" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void tests.TC002_LoginUser.enterCredential(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: enterCredential([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) ak@mail.com,(java.lang.String) ak@1234,(java.lang.String) Pass]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void tests.TC002_LoginUser.enterCredential(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: enterCredential([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) ak@mail.com,(java.lang.String) ak@1234,(java.lang.String) Pass]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:915)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterCredential -->
      </class> <!-- tests.TC002_LoginUser -->
    </test> <!-- TestChrome -->
  </suite> <!-- TestSuite -->
</testng-results>
